# Generated by Django 2.2.1 on 2019-05-14 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('TMOB', 'Mobile phone'), ('EML', 'E-mail'), ('SKP', 'Skype ID')], max_length=4)),
                ('value', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('descr', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=180)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weekend_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('week_discount', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('minimal_duration', models.IntegerField(default=1)),
                ('lock_start', models.DateField(blank=True, null=True)),
                ('lock_finish', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ('updated',),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateField()),
                ('finished', models.DateField()),
                ('canceled', models.BooleanField(default=False)),
                ('info2owner', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Property')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
